<?php

namespace app\widgets\news;

use yii\base\Widget;

class NewsItemWidget extends Widget
{
    const TYPE_FIRST = 1;
    const TYPE_SECOND = 2;
    const TYPE_DEFAULT = 3;

    public $type;
    public $data;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!$this->type) {
            return $this->type = self::TYPE_DEFAULT;
        }
        if (empty($data)) {
            return;
        }
    }

    public function run()
    {
        switch ($this->type) {
            case self::TYPE_FIRST:
                $view = 'items/first';
                break;
            case self::TYPE_SECOND:
                $view = 'items/second';
                break;
            case self::TYPE_DEFAULT:
            default:
                $view = 'items/default';
                break;

        }
        return $this->render($view, [
            'data' => $this->data,
            'type' => $this->type
        ]);


    }
}
