<?php

return [
    'items' => [
        'home' => ['label' => 'Home', 'url' => ['/admin/default/index'], 'classIcon' => 'icon-home', 'visible' => !Yii::$app->user->isGuest],
//        'subscribe' => ['label' => 'Đăng ký', 'url' => ['/admin/subscribe/index'], 'classIcon' => 'icon-filter', 'visible' => !Yii::$app->user->isGuest,
//            'items' => [
//                ['label' => 'Liên hệ', 'url' => ['/admin/subscribe/index'], 'visible' => !Yii::$app->user->isGuest],
//                ['label' => 'Nhận tin', 'url' => ['/admin/emailletter/index'], 'visible' => !Yii::$app->user->isGuest],
//            ],
//        ],
        'dongvat' => ['label' => 'Động vật', 'url' => ['/admin/dtvloai/index'], 'classIcon' => 'icon-fire', 'visible' => !Yii::$app->user->isGuest,
            'items' => [
                ['label' => 'Ngành', 'url' => ['/admin/dtvnganh/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Lớp', 'url' => ['/admin/dtvlop/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Bộ', 'url' => ['/admin/dtvbo/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Họ', 'url' => ['/admin/dtvho/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Loài', 'url' => ['/admin/dtvloai/index'], 'visible' => !Yii::$app->user->isGuest],
            ],
        ],
        'thucvat' => ['label' => 'Thực vật', 'url' => ['/admin/tvloai/index'], 'classIcon' => 'icon-fire', 'visible' => !Yii::$app->user->isGuest,
            'items' => [
                ['label' => 'Ngành', 'url' => ['/admin/tvnganh/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Lớp', 'url' => ['/admin/tvlop/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Bộ', 'url' => ['/admin/tvbo/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Họ', 'url' => ['/admin/tvho/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Loài', 'url' => ['/admin/tvloai/index'], 'visible' => !Yii::$app->user->isGuest],
            ],
        ],
        'news' => ['label' => 'Tin tức', 'url' => ['/admin/news/index'], 'classIcon' => 'icon-fire', 'visible' => !Yii::$app->user->isGuest,
            'items' => [
                ['label' => 'Danh sách', 'url' => ['/admin/news/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Thêm mới', 'url' => ['/admin/news/create'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Danh mục', 'url' => ['/admin/newscat/index'], 'visible' => !Yii::$app->user->isGuest],
            ],
        ],
        'menus' => ['label' => 'Menu', 'url' => ['/admin/menus/index'], 'classIcon' => 'icon-th', 'visible' => !Yii::$app->user->isGuest,
            'items' => [
                ['label' => 'Danh sách', 'url' => ['/admin/menus/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Thêm mới', 'url' => ['/admin/menus/create'], 'visible' => !Yii::$app->user->isGuest],
            ],
        ],
//        'boxpage' => ['label' => 'Box Page', 'url' => ['/admin/boxpage/index'], 'classIcon' => 'icon-fire', 'visible' => !Yii::$app->user->isGuest,
//            'items' => [
//                ['label' => 'Danh sách', 'url' => ['/admin/boxpage/index'], 'visible' => !Yii::$app->user->isGuest],
//                ['label' => 'Thêm mới', 'url' => ['/admin/boxpage/create'], 'visible' => !Yii::$app->user->isGuest],
//                ['label' => 'Danh mục', 'url' => ['/admin/boxpagecat/index'], 'visible' => !Yii::$app->user->isGuest],
//            ],
//        ],
        'banner' => ['label' => 'Banner', 'url' => ['/admin/banner/index'], 'classIcon' => 'icon-camera-retro', 'visible' => !Yii::$app->user->isGuest,
            'items' => [
                ['label' => 'Danh sách', 'url' => ['/admin/banner/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Thêm mới', 'url' => ['/admin/banner/create'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Danh mục', 'url' => ['/admin/bannercat/index'], 'visible' => !Yii::$app->user->isGuest],
            ],
        ],
        'sitecontact' => ['label' => 'Thông tin Site', 'url' => ['/admin/sitecontact/index'], 'classIcon' => 'icon-info', 'visible' => !Yii::$app->user->isGuest,
        ],
        'user' => ['label' => 'Quản lý User', 'url' => ['/admin/user/view'], 'classIcon' => 'icon-user-md', 'visible' => !Yii::$app->user->isGuest, 'items' => [
                ['label' => 'Danh sách User', 'url' => ['/admin/user/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Thêm mới User', 'url' => ['/admin/user/create'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Danh sách đổi mật khẩu', 'url' => ['/admin/user/listcpwd'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Thông tin User', 'url' => ['/admin/user/view'], 'visible' => !Yii::$app->user->isGuest],
            ],
        ],
        'seopage' => ['label' => 'Seo Page', 'url' => ['/admin/seopage/index'], 'classIcon' => 'icon-filter', 'visible' => !Yii::$app->user->isGuest,
            'items' => [
                ['label' => 'Danh sách', 'url' => ['/admin/seopage/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Thêm mới', 'url' => ['/admin/seopage/create'], 'visible' => !Yii::$app->user->isGuest],
            ],
        ],
        'config' => ['label' => 'Trợ giúp', 'url' => ['#'], 'classIcon' => 'icon-gear', 'visible' => !Yii::$app->user->isGuest, 'items' => [
                ['label' => 'Route Pages', 'url' => ['/admin/routepage/index'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Upload ảnh', 'url' => ['/admin/image/uploadimage'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Log Admin', 'url' => ['/admin/default/logadmin'], 'visible' => !Yii::$app->user->isGuest],
                ['label' => 'Log Lỗi Subscibe ', 'url' => ['/admin/logsubscribeerror/index'], 'visible' => !Yii::$app->user->isGuest],
            ],
        ],
        'right' => ['label' => 'Phân quyền', 'url' => ['/right'], 'classIcon' => 'icon-star', 'visible' => !Yii::$app->user->isGuest],
    ],
    'linkTemplateRoot' => '<a href="{url}" class="{classitem}">{icon}<span class="menu-text">{label}</span>{arrow}</a>',
    'linkTemplate' => '<a href="{url}" class="{classitem}">{icon}{label}{arrow}</a>',
    'labelTemplate' => '{icon}{label}{arrow}',
    'options' => [
        'class' => 'nav nav-list',
    ],
    'submenuTemplate' => "\n<ul class=\"submenu\">\n{items}\n</ul>\n",
    'activateParents' => true,
    'activateMap' => [
        'admin/banner/update' => 'admin/banner/index',
        'admin/menus/update' => 'admin/menus/index',
        'admin/boxpage/update' => 'admin/boxpage/index',
        'admin/boxpagecat/update' => 'admin/boxpagecat/index',
        'admin/boxpagecat/create' => 'admin/boxpagecat/index',
        'admin/newscat/update' => 'admin/newscat/index',
        'admin/newscat/create' => 'admin/newscat/index',
        'admin/news/update' => 'admin/news/index',
        'admin/bannercat/update' => 'admin/bannercat/index',
        'admin/bannercat/create' => 'admin/bannercat/index',
        'admin/sitecontact/update' => 'admin/sitecontact/index',
        'admin/dtvnganh/update' => 'admin/dtvnganh/index',
        'admin/dtvnganh/create' => 'admin/dtvnganh/index',
        'admin/dtvlop/update' => 'admin/dtvlop/index',
        'admin/dtvlop/create' => 'admin/dtvlop/index',
        'admin/dtvbo/update' => 'admin/dtvbo/index',
        'admin/dtvbo/create' => 'admin/dtvbo/index',
        'admin/dtvho/update' => 'admin/dtvho/index',
        'admin/dtvho/create' => 'admin/dtvho/index',
        'admin/dtvloai/update' => 'admin/dtvloai/index',
        'admin/dtvloai/create' => 'admin/dtvloai/index',
        'admin/tvnganh/update' => 'admin/tvnganh/index',
        'admin/tvnganh/create' => 'admin/tvnganh/index',
        'admin/tvlop/update' => 'admin/tvlop/index',
        'admin/tvlop/create' => 'admin/tvlop/index',
        'admin/tvbo/update' => 'admin/tvbo/index',
        'admin/tvbo/create' => 'admin/tvbo/index',
        'admin/tvho/update' => 'admin/tvho/index',
        'admin/tvho/create' => 'admin/tvho/index',
        'admin/tvloai/update' => 'admin/tvloai/index',
        'admin/tvloai/create' => 'admin/tvloai/index',
    ]
];

